assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-74118635-1

gems:
  - jekyll-assets
  - jekyll-sitemap

name: gstack_docs

permalink: pretty

url: # add site url
